<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>DATA_validator</RootNamespace>
    <AssemblyName>DATA_validator</AssemblyName>
    <StartupObject>DATA_validator.Program</StartupObject>
    <MyType>WindowsForms</MyType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>C:\Users\noela\Desktop\invincible\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>1</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateManifests>false</GenerateManifests>
    <SignManifests>false</SignManifests>
    <AssemblyTitle>DATA_validator</AssemblyTitle>
    <Product>PBIDS Household Data Validator</Product>
    <Copyright>Copyright ©  2010</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>WindowsApplication1.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022,42353,42354,42355</NoWarn>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineDebug>false</DefineDebug>
    <DocumentationFile>WindowsApplication1.xml</DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022,42353,42354,42355</NoWarn>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="HRS_Desktop.designer.vb" />
    <Compile Remove="HRS_Desktop.vb" />
    <Compile Remove="InvincibleCodes\Presentation\Form1.Designer.vb" />
    <Compile Remove="InvincibleCodes\Presentation\Form1.vb" />
    <Compile Remove="InvincibleCodes\Presentation\frmSQLQueryWindow.Designer.vb" />
    <Compile Remove="InvincibleCodes\Presentation\frmSQLQueryWindow.vb" />
    <Compile Remove="InvincibleCodes\Presentation\frmValidationMgmt.designer.vb" />
    <Compile Remove="InvincibleCodes\Presentation\frmValidationMgmt.vb" />
    <Compile Remove="InvincibleCodes\Presentation\frm_editConfigurations.designer.vb" />
    <Compile Remove="InvincibleCodes\Presentation\frm_editConfigurations.vb" />
    <Compile Remove="InvincibleCodes\Presentation\Frm_TheValidationsEditor.designer.vb" />
    <Compile Remove="InvincibleCodes\Presentation\Frm_TheValidationsEditor.vb" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="HRS_Desktop.resx" />
    <EmbeddedResource Remove="InvincibleCodes\Presentation\Form1.resx" />
    <EmbeddedResource Remove="InvincibleCodes\Presentation\frmSQLQueryWindow.resx" />
    <EmbeddedResource Remove="InvincibleCodes\Presentation\frmValidationMgmt.resx" />
    <EmbeddedResource Remove="InvincibleCodes\Presentation\frm_editConfigurations.resx" />
    <EmbeddedResource Remove="InvincibleCodes\Presentation\Frm_TheValidationsEditor.resx" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DgvFilterPopup, Version=1.1.0.0, Culture=neutral, processorArchitecture=MSIL" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="InvincibleCodes\Presentation\frmDataTransfer.designer.vb">
      <DependentUpon>frmDataTransfer.vb</DependentUpon>
    </Compile>
    <Compile Update="InvincibleCodes\Presentation\frm_TheEditorr.designer.vb">
      <DependentUpon>frm_TheEditorr.vb</DependentUpon>
    </Compile>
    <Compile Update="InvincibleCodes\Presentation\frm_ToValidateForm.designer.vb">
      <DependentUpon>frm_ToValidateForm.vb</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig">
      <Link>.editorconfig</Link>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.3.1">
      <Visible>False</Visible>
      <ProductName>Windows Installer 3.1</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.8" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="172.52.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.8" />
  </ItemGroup>
</Project>